package com.las.MachineManagement.Bean;
// Generated 2017-7-7 17:45:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Checkrecordb generated by hbm2java
 */
@Entity
@Table(name = "checkrecordb", catalog = "machinemanagement")
public class Checkrecordb implements java.io.Serializable {

	private Integer id;
	private Checkinfob checkinfob;
	private Integer monthNumber;
	private String networkBackup;
	private String harddriverBackup;
	private String logUploadAnalysis;
	private String firewallCheck;
	private String monthlyFloatAmount;
	private String serverStoppedInfo;
	private String signature;
	private String checkstate;
	private String state;

	public Checkrecordb() {
	}

	public Checkrecordb(Checkinfob checkinfob) {
		this.checkinfob = checkinfob;
	}

	public Checkrecordb(Checkinfob checkinfob, Integer monthNumber, String networkBackup, String harddriverBackup,
			String logUploadAnalysis, String firewallCheck, String monthlyFloatAmount, String serverStoppedInfo,
			String signature, String checkstate, String state) {
		this.checkinfob = checkinfob;
		this.monthNumber = monthNumber;
		this.networkBackup = networkBackup;
		this.harddriverBackup = harddriverBackup;
		this.logUploadAnalysis = logUploadAnalysis;
		this.firewallCheck = firewallCheck;
		this.monthlyFloatAmount = monthlyFloatAmount;
		this.serverStoppedInfo = serverStoppedInfo;
		this.signature = signature;
		this.checkstate = checkstate;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CheckInfoID", nullable = false)
	public Checkinfob getCheckinfob() {
		return this.checkinfob;
	}

	public void setCheckinfob(Checkinfob checkinfob) {
		this.checkinfob = checkinfob;
	}

	@Column(name = "MonthNumber")
	public Integer getMonthNumber() {
		return this.monthNumber;
	}

	public void setMonthNumber(Integer monthNumber) {
		this.monthNumber = monthNumber;
	}

	@Column(name = "NetworkBackup", length = 100)
	public String getNetworkBackup() {
		return this.networkBackup;
	}

	public void setNetworkBackup(String networkBackup) {
		this.networkBackup = networkBackup;
	}

	@Column(name = "HarddriverBackup", length = 100)
	public String getHarddriverBackup() {
		return this.harddriverBackup;
	}

	public void setHarddriverBackup(String harddriverBackup) {
		this.harddriverBackup = harddriverBackup;
	}

	@Column(name = "LogUploadAnalysis", length = 100)
	public String getLogUploadAnalysis() {
		return this.logUploadAnalysis;
	}

	public void setLogUploadAnalysis(String logUploadAnalysis) {
		this.logUploadAnalysis = logUploadAnalysis;
	}

	@Column(name = "FirewallCheck", length = 100)
	public String getFirewallCheck() {
		return this.firewallCheck;
	}

	public void setFirewallCheck(String firewallCheck) {
		this.firewallCheck = firewallCheck;
	}

	@Column(name = "MonthlyFloatAmount", length = 100)
	public String getMonthlyFloatAmount() {
		return this.monthlyFloatAmount;
	}

	public void setMonthlyFloatAmount(String monthlyFloatAmount) {
		this.monthlyFloatAmount = monthlyFloatAmount;
	}

	@Column(name = "ServerStoppedInfo", length = 100)
	public String getServerStoppedInfo() {
		return this.serverStoppedInfo;
	}

	public void setServerStoppedInfo(String serverStoppedInfo) {
		this.serverStoppedInfo = serverStoppedInfo;
	}

	@Column(name = "Signature", length = 100)
	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	@Column(name = "checkstate", length = 100)
	public String getCheckstate() {
		return this.checkstate;
	}

	public void setCheckstate(String checkstate) {
		this.checkstate = checkstate;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
