package com.las.MachineManagement.Bean;
// Generated 2017-4-12 10:59:31 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Checkinfob generated by hbm2java
 */
@Entity
@Table(name = "checkinfob", catalog = "machinemanagement")
public class Checkinfob implements java.io.Serializable {

	private Integer id;
	private Machineinfo machineinfo;
	private String flowNumber;
	private String propertyNumber;
	private String serialNumber;
	private String responsibilityDepartment;
	private String machineLocation;
	private String model;
	private String systemInfo;
	private String ipadd;
	private String machineUsage;
	private String mantainceStaff;
	private String year;
	private String comments;
	private String state;
	private Set<Checkrecordb> checkrecordbs = new HashSet<Checkrecordb>(0);

	public Checkinfob() {
	}

	public Checkinfob(Machineinfo machineinfo) {
		this.machineinfo = machineinfo;
	}

	public Checkinfob(Machineinfo machineinfo, String flowNumber, String propertyNumber, String serialNumber,
			String responsibilityDepartment, String machineLocation, String model, String systemInfo, String ipadd,
			String machineUsage, String mantainceStaff, String year, String comments, String state,
			Set<Checkrecordb> checkrecordbs) {
		this.machineinfo = machineinfo;
		this.flowNumber = flowNumber;
		this.propertyNumber = propertyNumber;
		this.serialNumber = serialNumber;
		this.responsibilityDepartment = responsibilityDepartment;
		this.machineLocation = machineLocation;
		this.model = model;
		this.systemInfo = systemInfo;
		this.ipadd = ipadd;
		this.machineUsage = machineUsage;
		this.mantainceStaff = mantainceStaff;
		this.year = year;
		this.comments = comments;
		this.state = state;
		this.checkrecordbs = checkrecordbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MachineInfoID", nullable = false)
	public Machineinfo getMachineinfo() {
		return this.machineinfo;
	}

	public void setMachineinfo(Machineinfo machineinfo) {
		this.machineinfo = machineinfo;
	}

	@Column(name = "FlowNumber", length = 100)
	public String getFlowNumber() {
		return this.flowNumber;
	}

	public void setFlowNumber(String flowNumber) {
		this.flowNumber = flowNumber;
	}

	@Column(name = "PropertyNumber", length = 100)
	public String getPropertyNumber() {
		return this.propertyNumber;
	}

	public void setPropertyNumber(String propertyNumber) {
		this.propertyNumber = propertyNumber;
	}

	@Column(name = "SerialNumber", length = 100)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "ResponsibilityDepartment", length = 100)
	public String getResponsibilityDepartment() {
		return this.responsibilityDepartment;
	}

	public void setResponsibilityDepartment(String responsibilityDepartment) {
		this.responsibilityDepartment = responsibilityDepartment;
	}

	@Column(name = "MachineLocation", length = 100)
	public String getMachineLocation() {
		return this.machineLocation;
	}

	public void setMachineLocation(String machineLocation) {
		this.machineLocation = machineLocation;
	}

	@Column(name = "Model", length = 100)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "SystemInfo", length = 100)
	public String getSystemInfo() {
		return this.systemInfo;
	}

	public void setSystemInfo(String systemInfo) {
		this.systemInfo = systemInfo;
	}

	@Column(name = "IPAdd", length = 100)
	public String getIpadd() {
		return this.ipadd;
	}

	public void setIpadd(String ipadd) {
		this.ipadd = ipadd;
	}

	@Column(name = "MachineUsage", length = 100)
	public String getMachineUsage() {
		return this.machineUsage;
	}

	public void setMachineUsage(String machineUsage) {
		this.machineUsage = machineUsage;
	}

	@Column(name = "MantainceStaff", length = 100)
	public String getMantainceStaff() {
		return this.mantainceStaff;
	}

	public void setMantainceStaff(String mantainceStaff) {
		this.mantainceStaff = mantainceStaff;
	}

	@Column(name = "year", length = 100)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "Comments", length = 500)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checkinfob")
	public Set<Checkrecordb> getCheckrecordbs() {
		return this.checkrecordbs;
	}

	public void setCheckrecordbs(Set<Checkrecordb> checkrecordbs) {
		this.checkrecordbs = checkrecordbs;
	}

}
