package com.las.MachineManagement.Bean;
// Generated 2017-7-7 17:45:23 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Checkinfoa generated by hbm2java
 */
@Entity
@Table(name = "checkinfoa", catalog = "machinemanagement")
public class Checkinfoa implements java.io.Serializable {

	private Integer id;
	private Machineinfo machineinfo;
	private String flowNumber;
	private String propertyNumber;
	private String serialNumber;
	private String responsibilityDepartment;
	private String machineLocation;
	private String model;
	private String systemInfo;
	private String ipadd;
	private String machineUsage;
	private String mantainceStaff;
	private String backupContent;
	private String backupContentChange1;
	private String backupContentChange2;
	private String fileDirectory;
	private String fileDirectoryChange1;
	private String fileDirectoryChange2;
	private String backupPeriod;
	private String backupPeriodChange1;
	private String backupPeriodChange2;
	private String year;
	private String state;
	private Set<Checkrecorda> checkrecordas = new HashSet<Checkrecorda>(0);

	public Checkinfoa() {
	}

	public Checkinfoa(Machineinfo machineinfo) {
		this.machineinfo = machineinfo;
	}

	public Checkinfoa(Machineinfo machineinfo, String flowNumber, String propertyNumber, String serialNumber,
			String responsibilityDepartment, String machineLocation, String model, String systemInfo, String ipadd,
			String machineUsage, String mantainceStaff, String backupContent, String backupContentChange1,
			String backupContentChange2, String fileDirectory, String fileDirectoryChange1, String fileDirectoryChange2,
			String backupPeriod, String backupPeriodChange1, String backupPeriodChange2, String year, String state,
			Set<Checkrecorda> checkrecordas) {
		this.machineinfo = machineinfo;
		this.flowNumber = flowNumber;
		this.propertyNumber = propertyNumber;
		this.serialNumber = serialNumber;
		this.responsibilityDepartment = responsibilityDepartment;
		this.machineLocation = machineLocation;
		this.model = model;
		this.systemInfo = systemInfo;
		this.ipadd = ipadd;
		this.machineUsage = machineUsage;
		this.mantainceStaff = mantainceStaff;
		this.backupContent = backupContent;
		this.backupContentChange1 = backupContentChange1;
		this.backupContentChange2 = backupContentChange2;
		this.fileDirectory = fileDirectory;
		this.fileDirectoryChange1 = fileDirectoryChange1;
		this.fileDirectoryChange2 = fileDirectoryChange2;
		this.backupPeriod = backupPeriod;
		this.backupPeriodChange1 = backupPeriodChange1;
		this.backupPeriodChange2 = backupPeriodChange2;
		this.year = year;
		this.state = state;
		this.checkrecordas = checkrecordas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MachineInfoID", nullable = false)
	public Machineinfo getMachineinfo() {
		return this.machineinfo;
	}

	public void setMachineinfo(Machineinfo machineinfo) {
		this.machineinfo = machineinfo;
	}

	@Column(name = "FlowNumber", length = 100)
	public String getFlowNumber() {
		return this.flowNumber;
	}

	public void setFlowNumber(String flowNumber) {
		this.flowNumber = flowNumber;
	}

	@Column(name = "PropertyNumber", length = 100)
	public String getPropertyNumber() {
		return this.propertyNumber;
	}

	public void setPropertyNumber(String propertyNumber) {
		this.propertyNumber = propertyNumber;
	}

	@Column(name = "SerialNumber", length = 100)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "ResponsibilityDepartment", length = 100)
	public String getResponsibilityDepartment() {
		return this.responsibilityDepartment;
	}

	public void setResponsibilityDepartment(String responsibilityDepartment) {
		this.responsibilityDepartment = responsibilityDepartment;
	}

	@Column(name = "MachineLocation", length = 100)
	public String getMachineLocation() {
		return this.machineLocation;
	}

	public void setMachineLocation(String machineLocation) {
		this.machineLocation = machineLocation;
	}

	@Column(name = "Model", length = 100)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "SystemInfo", length = 100)
	public String getSystemInfo() {
		return this.systemInfo;
	}

	public void setSystemInfo(String systemInfo) {
		this.systemInfo = systemInfo;
	}

	@Column(name = "IPAdd", length = 100)
	public String getIpadd() {
		return this.ipadd;
	}

	public void setIpadd(String ipadd) {
		this.ipadd = ipadd;
	}

	@Column(name = "MachineUsage", length = 100)
	public String getMachineUsage() {
		return this.machineUsage;
	}

	public void setMachineUsage(String machineUsage) {
		this.machineUsage = machineUsage;
	}

	@Column(name = "MantainceStaff", length = 100)
	public String getMantainceStaff() {
		return this.mantainceStaff;
	}

	public void setMantainceStaff(String mantainceStaff) {
		this.mantainceStaff = mantainceStaff;
	}

	@Column(name = "BackupContent", length = 100)
	public String getBackupContent() {
		return this.backupContent;
	}

	public void setBackupContent(String backupContent) {
		this.backupContent = backupContent;
	}

	@Column(name = "BackupContentChange1", length = 100)
	public String getBackupContentChange1() {
		return this.backupContentChange1;
	}

	public void setBackupContentChange1(String backupContentChange1) {
		this.backupContentChange1 = backupContentChange1;
	}

	@Column(name = "BackupContentChange2", length = 100)
	public String getBackupContentChange2() {
		return this.backupContentChange2;
	}

	public void setBackupContentChange2(String backupContentChange2) {
		this.backupContentChange2 = backupContentChange2;
	}

	@Column(name = "FileDirectory", length = 100)
	public String getFileDirectory() {
		return this.fileDirectory;
	}

	public void setFileDirectory(String fileDirectory) {
		this.fileDirectory = fileDirectory;
	}

	@Column(name = "FileDirectoryChange1", length = 100)
	public String getFileDirectoryChange1() {
		return this.fileDirectoryChange1;
	}

	public void setFileDirectoryChange1(String fileDirectoryChange1) {
		this.fileDirectoryChange1 = fileDirectoryChange1;
	}

	@Column(name = "FileDirectoryChange2", length = 100)
	public String getFileDirectoryChange2() {
		return this.fileDirectoryChange2;
	}

	public void setFileDirectoryChange2(String fileDirectoryChange2) {
		this.fileDirectoryChange2 = fileDirectoryChange2;
	}

	@Column(name = "BackupPeriod", length = 100)
	public String getBackupPeriod() {
		return this.backupPeriod;
	}

	public void setBackupPeriod(String backupPeriod) {
		this.backupPeriod = backupPeriod;
	}

	@Column(name = "BackupPeriodChange1", length = 100)
	public String getBackupPeriodChange1() {
		return this.backupPeriodChange1;
	}

	public void setBackupPeriodChange1(String backupPeriodChange1) {
		this.backupPeriodChange1 = backupPeriodChange1;
	}

	@Column(name = "BackupPeriodChange2", length = 100)
	public String getBackupPeriodChange2() {
		return this.backupPeriodChange2;
	}

	public void setBackupPeriodChange2(String backupPeriodChange2) {
		this.backupPeriodChange2 = backupPeriodChange2;
	}

	@Column(name = "year", length = 100)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checkinfoa")
	public Set<Checkrecorda> getCheckrecordas() {
		return this.checkrecordas;
	}

	public void setCheckrecordas(Set<Checkrecorda> checkrecordas) {
		this.checkrecordas = checkrecordas;
	}

}
