package com.las.MachineManagement.Bean;
// Generated 2017-7-7 17:45:23 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Emailconfiguration generated by hbm2java
 */
@Entity
@Table(name = "emailconfiguration", catalog = "machinemanagement")
public class Emailconfiguration implements java.io.Serializable {

	private Integer id;
	private String server;
	private String port;
	private Boolean useSsl;
	private String userName;
	private String passWord;
	private String state;
	private Set<Users> userses = new HashSet<Users>(0);

	public Emailconfiguration() {
	}

	public Emailconfiguration(String server, String port, Boolean useSsl, String userName, String passWord,
			String state, Set<Users> userses) {
		this.server = server;
		this.port = port;
		this.useSsl = useSsl;
		this.userName = userName;
		this.passWord = passWord;
		this.state = state;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "server", length = 100)
	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	@Column(name = "port", length = 100)
	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	@Column(name = "UseSSL")
	public Boolean getUseSsl() {
		return this.useSsl;
	}

	public void setUseSsl(Boolean useSsl) {
		this.useSsl = useSsl;
	}

	@Column(name = "UserName", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PassWord", length = 100)
	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emailconfiguration")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
