package com.las.MachineManagement.Bean;
// Generated 2017-4-12 10:59:31 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emailrecord generated by hbm2java
 */
@Entity
@Table(name = "emailrecord", catalog = "machinemanagement")
public class Emailrecord implements java.io.Serializable {

	private Integer id;
	private Machineinfo machineinfo;
	private Integer year;
	private Integer month;
	private String emailSender;
	private String emailReceiver;
	private String emailContent;
	private Date createDatetime;
	private Date updateDatetime;
	private String state;

	public Emailrecord() {
	}

	public Emailrecord(Machineinfo machineinfo, Integer year, Integer month, String emailSender, String emailReceiver,
			String emailContent, Date createDatetime, Date updateDatetime, String state) {
		this.machineinfo = machineinfo;
		this.year = year;
		this.month = month;
		this.emailSender = emailSender;
		this.emailReceiver = emailReceiver;
		this.emailContent = emailContent;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MachineinfoID")
	public Machineinfo getMachineinfo() {
		return this.machineinfo;
	}

	public void setMachineinfo(Machineinfo machineinfo) {
		this.machineinfo = machineinfo;
	}

	@Column(name = "Year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "Month")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Column(name = "EmailSender")
	public String getEmailSender() {
		return this.emailSender;
	}

	public void setEmailSender(String emailSender) {
		this.emailSender = emailSender;
	}

	@Column(name = "EmailReceiver")
	public String getEmailReceiver() {
		return this.emailReceiver;
	}

	public void setEmailReceiver(String emailReceiver) {
		this.emailReceiver = emailReceiver;
	}

	@Column(name = "EmailContent", length = 2000)
	public String getEmailContent() {
		return this.emailContent;
	}

	public void setEmailContent(String emailContent) {
		this.emailContent = emailContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDatetime", length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateDatetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
