package com.las.MachineManagement.Bean;
// Generated 2017-7-3 9:45:31 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Functions generated by hbm2java
 */
@Entity
@Table(name = "functions", catalog = "machinemanagement")
public class Functions implements java.io.Serializable {

	private Integer id;
	private String functionname;
	private String htmlid;
	private String functionurl;
	private String functionicon;
	private String description;
	private Integer displayorder;
	private Date updatetime;
	private String state;

	public Functions() {
	}

	public Functions(String functionname, String htmlid, String functionurl, String functionicon, String description,
			Integer displayorder, Date updatetime, String state) {
		this.functionname = functionname;
		this.htmlid = htmlid;
		this.functionurl = functionurl;
		this.functionicon = functionicon;
		this.description = description;
		this.displayorder = displayorder;
		this.updatetime = updatetime;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "functionname", length = 100)
	public String getFunctionname() {
		return this.functionname;
	}

	public void setFunctionname(String functionname) {
		this.functionname = functionname;
	}

	@Column(name = "htmlid", length = 200)
	public String getHtmlid() {
		return this.htmlid;
	}

	public void setHtmlid(String htmlid) {
		this.htmlid = htmlid;
	}

	@Column(name = "functionurl", length = 2000)
	public String getFunctionurl() {
		return this.functionurl;
	}

	public void setFunctionurl(String functionurl) {
		this.functionurl = functionurl;
	}

	@Column(name = "functionicon", length = 2000)
	public String getFunctionicon() {
		return this.functionicon;
	}

	public void setFunctionicon(String functionicon) {
		this.functionicon = functionicon;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "displayorder")
	public Integer getDisplayorder() {
		return this.displayorder;
	}

	public void setDisplayorder(Integer displayorder) {
		this.displayorder = displayorder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
