package com.las.MachineManagement.Bean;
// Generated 2017-7-3 9:45:31 by Hibernate Tools 5.2.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Machineinfo generated by hbm2java
 */
@Entity
@Table(name = "machineinfo", catalog = "machinemanagement")
public class Machineinfo implements java.io.Serializable {

	private Integer id;
	private String propertyNumber;
	private String machineLocation;
	private String model;
	private String ipadd;
	private String machineUsage;
	private String department;
	private String responsible;
	private String responsibleEmail;
	private String responsibleContactNumber;
	private String systemInfo;
	private Date purchaseTime;
	private String price;
	private String project;
	private String comments;
	private String registrant;
	private Date moveInTime;
	private Date updateTime;
	private String purchaser;
	private String purchaseMethod;
	private String supplier;
	private String supplierContact;
	private String supplierContactNumber;
	private String machineType;
	private String state;
	private String propertyName;
	private Set<Checkinfob> checkinfobs = new HashSet<Checkinfob>(0);
	private Set<Checkinfoa> checkinfoas = new HashSet<Checkinfoa>(0);
	private Set<Transferrecord> transferrecords = new HashSet<Transferrecord>(0);
	private Set<Emailrecord> emailrecords = new HashSet<Emailrecord>(0);
	
	
	public int responsibleUserId;
	
	/**
	 * @return the responsibleUserId
	 */
	public int getResponsibleUserId() {
		return responsibleUserId;
	}




	/**
	 * @param responsibleUserId the responsibleUserId to set
	 */
	public void setResponsibleUserId(int responsibleUserId) {
		this.responsibleUserId = responsibleUserId;
	}




	public String emailList;
	private String checkStateA;
	private String checkStateB;
	private int displayNumber;
	
    public List<Transferrecord> transferRecordList;
    public List<Checkinfoa> checkInfoAList;
    public List<Checkinfob> checkInfoBList;
    
	 public  Machineinfo(){
		 this.transferRecordList=new ArrayList<Transferrecord>();
		 this.checkInfoAList=new ArrayList<Checkinfoa>();
		 this.checkInfoBList=new ArrayList<Checkinfob>();
	 }
	 
	 
 

	public Machineinfo(String propertyNumber, String machineLocation, String model, String ipadd, String machineUsage,
			String department, String responsible, String responsibleEmail, String responsibleContactNumber,
			String systemInfo, Date purchaseTime, String price, String project, String comments, String registrant,
			Date moveInTime, Date updateTime, String purchaser, String purchaseMethod, String supplier,
			String supplierContact, String supplierContactNumber, String machineType, String state, String propertyName,
			Set<Checkinfob> checkinfobs, Set<Checkinfoa> checkinfoas, Set<Transferrecord> transferrecords,
			Set<Emailrecord> emailrecords) {
		this.propertyNumber = propertyNumber;
		this.machineLocation = machineLocation;
		this.model = model;
		this.ipadd = ipadd;
		this.machineUsage = machineUsage;
		this.department = department;
		this.responsible = responsible;
		this.responsibleEmail = responsibleEmail;
		this.responsibleContactNumber = responsibleContactNumber;
		this.systemInfo = systemInfo;
		this.purchaseTime = purchaseTime;
		this.price = price;
		this.project = project;
		this.comments = comments;
		this.registrant = registrant;
		this.moveInTime = moveInTime;
		this.updateTime = updateTime;
		this.purchaser = purchaser;
		this.purchaseMethod = purchaseMethod;
		this.supplier = supplier;
		this.supplierContact = supplierContact;
		this.supplierContactNumber = supplierContactNumber;
		this.machineType = machineType;
		this.state = state;
		this.propertyName = propertyName;
		this.checkinfobs = checkinfobs;
		this.checkinfoas = checkinfoas;
		this.transferrecords = transferrecords;
		this.emailrecords = emailrecords;
	}

	
	
	
	public  Machineinfo(int id ,String PropertyNumber ,String MachineLocation ,String Model ,String IPAdd ,String MachineUsage ,String Department ,String Responsible,String ResponsibleEmail,String ResponsibleContactNumber,String SystemInfo ,Date PurchaseTime,String Price,String Project,String Comments,String Registrant,Date MoveInTime,Date UpdateTime,String Purchaser,String PurchaseMethod, String Supplier, String SupplierContact, String SupplierContactNumber,String PropertyName)
	 {
		this.id = id;
		this.propertyNumber = PropertyNumber;
		this.machineLocation = MachineLocation;
		this.model = Model;
		this.ipadd = IPAdd;
		this.machineUsage = MachineUsage;
		this.department = Department;
		this.responsible = Responsible;
		this.responsibleEmail=ResponsibleEmail;
		this.responsibleContactNumber=ResponsibleContactNumber;
		this.systemInfo = SystemInfo;
		this.purchaseTime = PurchaseTime;
		this.price=Price;
		this.project=Project;
		this.comments=Comments;
		this.registrant=Registrant;
		this.moveInTime=MoveInTime;
		this.updateTime=UpdateTime;
		this.purchaser=Purchaser;
		this.purchaseMethod=PurchaseMethod;
		this.supplier=Supplier;
		this.supplierContact=SupplierContact;
		this.supplierContactNumber=SupplierContactNumber;
		this.propertyName=PropertyName;
 
		
		
		//当月检查表A的状态默认是未检查
		this.checkStateA="0";
		//当月检查表B的状态默认是未检查
		this.checkStateB="0";
		 this.transferRecordList=new ArrayList<Transferrecord>();
		 this.checkInfoAList=new ArrayList<Checkinfoa>();
		 this.checkInfoBList=new ArrayList<Checkinfob>();
	 }
	 
	 //按ID搜索machineinfo时，需要显示emaillist
	 public  Machineinfo(int id ,String PropertyNumber ,String MachineLocation ,String Model ,String IPAdd ,String MachineUsage ,String Department ,String Responsible,String ResponsibleEmail,String ResponsibleContactNumber,String SystemInfo ,Date PurchaseTime,String Price,String Project,String Comments,String Registrant,Date MoveInTime,Date UpdateTime,String EmailList,String Purchaser,String PurchaseMethod, String Supplier, String SupplierContact, String SupplierContactNumber,String PropertyName)
	 {
		this.id = id;
		this.propertyNumber = PropertyNumber;
		this.machineLocation = MachineLocation;
		this.model = Model;
		this.ipadd = IPAdd;
		this.machineUsage = MachineUsage;
		this.department = Department;
		this.responsible = Responsible;
		this.responsibleEmail=ResponsibleEmail;
		this.responsibleContactNumber=ResponsibleContactNumber;
		this.systemInfo = SystemInfo;
		this.purchaseTime = PurchaseTime;
		this.price=Price;
		this.project=Project;
		this.comments=Comments;
		this.registrant=Registrant;
		this.moveInTime=MoveInTime;
		this.updateTime=UpdateTime;
		this.emailList=EmailList;
		
		this.purchaser=Purchaser;
		this.purchaseMethod=PurchaseMethod;
		this.supplier=Supplier;
		this.supplierContact=SupplierContact;
		this.supplierContactNumber=SupplierContactNumber;
		this.propertyName=PropertyName;
		

		
		
		//当月检查表A的状态默认是未检查
		this.checkStateA="0";
		//当月检查表B的状态默认是未检查
		this.checkStateB="0";
		 this.transferRecordList=new ArrayList<Transferrecord>();
		 this.checkInfoAList=new ArrayList<Checkinfoa>();
		 this.checkInfoBList=new ArrayList<Checkinfob>();
	 }
	 
	 
	 
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PropertyNumber", length = 100)
	public String getPropertyNumber() {
		return this.propertyNumber;
	}

	public void setPropertyNumber(String propertyNumber) {
		this.propertyNumber = propertyNumber;
	}

	@Column(name = "MachineLocation", length = 100)
	public String getMachineLocation() {
		return this.machineLocation;
	}

	public void setMachineLocation(String machineLocation) {
		this.machineLocation = machineLocation;
	}

	@Column(name = "Model", length = 100)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "IPAdd", length = 100)
	public String getIpadd() {
		return this.ipadd;
	}

	public void setIpadd(String ipadd) {
		this.ipadd = ipadd;
	}

	@Column(name = "MachineUsage", length = 100)
	public String getMachineUsage() {
		return this.machineUsage;
	}

	public void setMachineUsage(String machineUsage) {
		this.machineUsage = machineUsage;
	}

	@Column(name = "Department", length = 100)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "Responsible", length = 100)
	public String getResponsible() {
		return this.responsible;
	}

	public void setResponsible(String responsible) {
		this.responsible = responsible;
	}

	@Column(name = "ResponsibleEmail", length = 200)
	public String getResponsibleEmail() {
		return this.responsibleEmail;
	}

	public void setResponsibleEmail(String responsibleEmail) {
		this.responsibleEmail = responsibleEmail;
	}

	@Column(name = "ResponsibleContactNumber", length = 100)
	public String getResponsibleContactNumber() {
		return this.responsibleContactNumber;
	}

	public void setResponsibleContactNumber(String responsibleContactNumber) {
		this.responsibleContactNumber = responsibleContactNumber;
	}

	@Column(name = "SystemInfo", length = 100)
	public String getSystemInfo() {
		return this.systemInfo;
	}

	public void setSystemInfo(String systemInfo) {
		this.systemInfo = systemInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PurchaseTime", length = 19)
	public Date getPurchaseTime() {
		return this.purchaseTime;
	}

	public void setPurchaseTime(Date purchaseTime) {
		this.purchaseTime = purchaseTime;
	}

	@Column(name = "Price", length = 100)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "Project", length = 5000)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "Comments", length = 5000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "Registrant", length = 100)
	public String getRegistrant() {
		return this.registrant;
	}

	public void setRegistrant(String registrant) {
		this.registrant = registrant;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MoveInTime", length = 19)
	public Date getMoveInTime() {
		return this.moveInTime;
	}

	public void setMoveInTime(Date moveInTime) {
		this.moveInTime = moveInTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "Purchaser", length = 100)
	public String getPurchaser() {
		return this.purchaser;
	}

	public void setPurchaser(String purchaser) {
		this.purchaser = purchaser;
	}

	@Column(name = "PurchaseMethod", length = 100)
	public String getPurchaseMethod() {
		return this.purchaseMethod;
	}

	public void setPurchaseMethod(String purchaseMethod) {
		this.purchaseMethod = purchaseMethod;
	}

	@Column(name = "Supplier", length = 100)
	public String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	@Column(name = "SupplierContact", length = 100)
	public String getSupplierContact() {
		return this.supplierContact;
	}

	public void setSupplierContact(String supplierContact) {
		this.supplierContact = supplierContact;
	}

	@Column(name = "SupplierContactNumber", length = 100)
	public String getSupplierContactNumber() {
		return this.supplierContactNumber;
	}

	public void setSupplierContactNumber(String supplierContactNumber) {
		this.supplierContactNumber = supplierContactNumber;
	}

	@Column(name = "MachineType", length = 100)
	public String getMachineType() {
		return this.machineType;
	}

	public void setMachineType(String machineType) {
		this.machineType = machineType;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "PropertyName")
	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "machineinfo")
	public Set<Checkinfob> getCheckinfobs() {
		return this.checkinfobs;
	}

	public void setCheckinfobs(Set<Checkinfob> checkinfobs) {
		this.checkinfobs = checkinfobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "machineinfo")
	public Set<Checkinfoa> getCheckinfoas() {
		return this.checkinfoas;
	}

	public void setCheckinfoas(Set<Checkinfoa> checkinfoas) {
		this.checkinfoas = checkinfoas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "machineinfo")
	public Set<Transferrecord> getTransferrecords() {
		return this.transferrecords;
	}

	public void setTransferrecords(Set<Transferrecord> transferrecords) {
		this.transferrecords = transferrecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "machineinfo")
	public Set<Emailrecord> getEmailrecords() {
		return this.emailrecords;
	}

	public void setEmailrecords(Set<Emailrecord> emailrecords) {
		this.emailrecords = emailrecords;
	}




	/**
	 * @return the emailList
	 */
	public String getEmailList() {
		return emailList;
	}




	/**
	 * @param emailList the emailList to set
	 */
	public void setEmailList(String emailList) {
		this.emailList = emailList;
	}




	/**
	 * @return the checkStateA
	 */
	public String getCheckStateA() {
		return checkStateA;
	}




	/**
	 * @param checkStateA the checkStateA to set
	 */
	public void setCheckStateA(String checkStateA) {
		this.checkStateA = checkStateA;
	}




	/**
	 * @return the checkStateB
	 */
	public String getCheckStateB() {
		return checkStateB;
	}




	/**
	 * @param checkStateB the checkStateB to set
	 */
	public void setCheckStateB(String checkStateB) {
		this.checkStateB = checkStateB;
	}




	/**
	 * @return the displayNumber
	 */
	public int getDisplayNumber() {
		return displayNumber;
	}




	/**
	 * @param displayNumber the displayNumber to set
	 */
	public void setDisplayNumber(int displayNumber) {
		this.displayNumber = displayNumber;
	}




	/**
	 * @return the transferRecordList
	 */
	public List<Transferrecord> getTransferRecordList() {
		return transferRecordList;
	}




	/**
	 * @param transferRecordList the transferRecordList to set
	 */
	public void setTransferRecordList(List<Transferrecord> transferRecordList) {
		this.transferRecordList = transferRecordList;
	}




	/**
	 * @return the checkInfoAList
	 */
	public List<Checkinfoa> getCheckInfoAList() {
		return checkInfoAList;
	}




	/**
	 * @param checkInfoAList the checkInfoAList to set
	 */
	public void setCheckInfoAList(List<Checkinfoa> checkInfoAList) {
		this.checkInfoAList = checkInfoAList;
	}




	/**
	 * @return the checkInfoBList
	 */
	public List<Checkinfob> getCheckInfoBList() {
		return checkInfoBList;
	}




	/**
	 * @param checkInfoBList the checkInfoBList to set
	 */
	public void setCheckInfoBList(List<Checkinfob> checkInfoBList) {
		this.checkInfoBList = checkInfoBList;
	}

	
	
	
}
