package com.las.MachineManagement.Bean;
// Generated 2017-4-12 10:59:31 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transferrecord generated by hbm2java
 */
@Entity
@Table(name = "transferrecord", catalog = "machinemanagement")
public class Transferrecord implements java.io.Serializable {

	private Integer id;
	private Machineinfo machineinfo;
	private String preOwner;
	private String preOwnerEmail;
	private String curOwner;
	private String curOwnerEmail;
	private Integer preid;
	private String department;
	private String reason;
	private Date happenTime;
	private String state;

	public Transferrecord() {
	}

	public Transferrecord(Machineinfo machineinfo) {
		this.machineinfo = machineinfo;
	}

	public Transferrecord(Machineinfo machineinfo, String preOwner, String preOwnerEmail, String curOwner,
			String curOwnerEmail, Integer preid, String department, String reason, Date happenTime, String state) {
		this.machineinfo = machineinfo;
		this.preOwner = preOwner;
		this.preOwnerEmail = preOwnerEmail;
		this.curOwner = curOwner;
		this.curOwnerEmail = curOwnerEmail;
		this.preid = preid;
		this.department = department;
		this.reason = reason;
		this.happenTime = happenTime;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MachineInfoID", nullable = false)
	public Machineinfo getMachineinfo() {
		return this.machineinfo;
	}

	public void setMachineinfo(Machineinfo machineinfo) {
		this.machineinfo = machineinfo;
	}

	@Column(name = "PreOwner", length = 100)
	public String getPreOwner() {
		return this.preOwner;
	}

	public void setPreOwner(String preOwner) {
		this.preOwner = preOwner;
	}

	@Column(name = "PreOwnerEmail", length = 200)
	public String getPreOwnerEmail() {
		return this.preOwnerEmail;
	}

	public void setPreOwnerEmail(String preOwnerEmail) {
		this.preOwnerEmail = preOwnerEmail;
	}

	@Column(name = "CurOwner", length = 100)
	public String getCurOwner() {
		return this.curOwner;
	}

	public void setCurOwner(String curOwner) {
		this.curOwner = curOwner;
	}

	@Column(name = "CurOwnerEmail", length = 200)
	public String getCurOwnerEmail() {
		return this.curOwnerEmail;
	}

	public void setCurOwnerEmail(String curOwnerEmail) {
		this.curOwnerEmail = curOwnerEmail;
	}

	@Column(name = "Preid")
	public Integer getPreid() {
		return this.preid;
	}

	public void setPreid(Integer preid) {
		this.preid = preid;
	}

	@Column(name = "department", length = 100)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "reason", length = 2000)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HappenTime", length = 19)
	public Date getHappenTime() {
		return this.happenTime;
	}

	public void setHappenTime(Date happenTime) {
		this.happenTime = happenTime;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
