package com.las.MachineManagement.Bean;
// Generated 2017-7-7 17:45:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UsersMachineinforesponsibleR generated by hbm2java
 */
@Entity
@Table(name = "users_machineinforesponsible_r", catalog = "machinemanagement")
public class UsersMachineinforesponsibleR implements java.io.Serializable {

	private Integer id;
	private String machineinfoid;
	private String userid;
	private String state;

	public UsersMachineinforesponsibleR() {
	}

	public UsersMachineinforesponsibleR(String machineinfoid, String userid, String state) {
		this.machineinfoid = machineinfoid;
		this.userid = userid;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "machineinfoid", length = 100)
	public String getMachineinfoid() {
		return this.machineinfoid;
	}

	public void setMachineinfoid(String machineinfoid) {
		this.machineinfoid = machineinfoid;
	}

	@Column(name = "userid", length = 2000)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
