package com.las.MachineManagement.Bean;
// Generated 2017-7-7 17:45:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserroleFunctionsR generated by hbm2java
 */
@Entity
@Table(name = "userrole_functions_r", catalog = "machinemanagement")
public class UserroleFunctionsR implements java.io.Serializable {

	private Integer id;
	private String userroleid;
	private String functionid;
	private String state;

	public UserroleFunctionsR() {
	}

	public UserroleFunctionsR(String userroleid, String functionid, String state) {
		this.userroleid = userroleid;
		this.functionid = functionid;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userroleid", length = 100)
	public String getUserroleid() {
		return this.userroleid;
	}

	public void setUserroleid(String userroleid) {
		this.userroleid = userroleid;
	}

	@Column(name = "functionid", length = 2000)
	public String getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(String functionid) {
		this.functionid = functionid;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
